on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
#    outputs:
#       output1: ${{ steps.step1.outputs.test }}
#       output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: |
          echo 
          json_string='{"name": "John", "age": 30, "city": "New York"}'
          echo "person=$json_string" >> "$GITHUB_OUTPUT"
          echo "out1=$GITHUB_OUTPUT" >> "$GITHUB_OUTPUT"
      - id: step2
        run: |
          echo ${{steps.step1.outputs.person}}
          cat ${{steps.step1.outputs.out1}}
          echo "test=world" >> "$GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT | xargs echo
          printenv
      - id: step3
        run: |
          printenv
  job2:
     runs-on: ubuntu-latest
     needs: job1
     steps:
       - env:
           OUTPUT1: ${{needs.job1.outputs.output1}}
           OUTPUT2: ${{needs.job1.outputs.output2}}
         run: |
           echo "$OUTPUT1 $OUTPUT2"
           echo ${{steps.step1.outputs.person}}
